### ISSUE TITLE
企画のふわふわを無くす

### ISSUE THREAD

**Issue by KosugiAyano** [KosugiAyano/Novel#2]
以下を確定させる

1. タイトル
2. コンセプト
3. 世界観
4. グラフィックのテイスト
5. サウンドのテイスト

**Comment by DaisukeSaitho** [comment]
タイトルは「〇〇〇〇ボール」に決定しました。

**Comment by DaisukeSaitho** [comment]
コンセプト「授業課題でも探索がしたい」に決定しました。

**Comment by DaisukeSaitho** [comment]
世界観は「日本の八王子市、日本工学院八王子専門学校、そこのゲームクリエイター科の主人公は、授業で赤点を取ってしまう。このまま母に報告するとまずいと感じた主人公は、〇〇〇〇ボールを集めて点数を偽装することを思いつき、キャンパス内を冒険する旅にでる。」に決定しました。

**Comment by DaisukeSaitho** [comment]
グラフィックのテイストは「現代の日本、キャラクタはかまいたちの夜みたいに青塗りを透過したようなもの」に決定しました。

**Comment by DaisukeSaitho** [comment]
サウンドのテイストは「現代の日本、日常できこえてくるようなもの、大圖先生の場面はホラーテイストで」に決定しました。

**Comment by DaisukeSaitho** [comment]
以上でこのIssueで行う作業は終了しました。
